serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
        - http://localhost:4455
      allowed_methods:
        - POST
        - GET
        - PUT
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
        - X-Session-Token
        - X-CSRF-Token
  admin:
    base_url: http://localhost:4434/

dsn: postgres://asest:asest123@postgres:5432/asest?sslmode=disable

log:
  level: debug

identity:
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

selfservice:
  default_browser_return_url: http://localhost:3000/
  flows:
    error:
      ui_url: http://localhost:3000/error
    settings:
      ui_url: http://localhost:3000/settings
      privileged_session_max_age: 15m
    recovery:
      enabled: true
      ui_url: http://localhost:3000/recovery
    verification:
      enabled: true
      ui_url: http://localhost:3000/verification
      after:
        default_browser_return_url: http://localhost:3000/
    login:
      ui_url: http://localhost:3000/login
      lifespan: 10m
    registration:
      ui_url: http://localhost:3000/registration
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: session

# Disable CSRF protection for development
serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
        - http://localhost:4455
      allowed_methods:
        - POST
        - GET
        - PUT
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
        - X-Session-Token
        - X-CSRF-Token
    csrf:
      enabled: false

session:
  cookie:
    name: ory_kratos_session
    same_site: Lax
  lifespan: 720h

hashers:
  argon2:
    parallelism: 1
    memory: "128MB"
    iterations: 2
    salt_length: 16
    key_length: 16

courier:
  smtp:
    connection_uri: smtps://test:test@localhost:1025/?skip_ssl_verify=true