serve:
  public:
    base_url: http://localhost:4433/
  admin:
    base_url: http://localhost:4434/

dsn: postgres://asest:asest123@postgres:5432/asest?sslmode=disable

log:
  level: debug

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

selfservice:
  default_browser_return_url: http://localhost:4455/
  flows:
    error:
      ui_url: http://localhost:4455/error
    settings:
      ui_url: http://localhost:4455/settings
      privileged_session_max_age: 15m
    recovery:
      enabled: true
      ui_url: http://localhost:4455/recovery
    verification:
      enabled: true
      ui_url: http://localhost:4455/verification
      after:
        default_browser_return_url: http://localhost:4455/
    login:
      ui_url: http://localhost:4455/login
      lifespan: 10m
    registration:
      ui_url: http://localhost:4455/registration
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: session

session:
  cookie:
    secure: false
  lifespan: 720h

hashers:
  argon2:
    parallelism: 1
    memory: 131072
    iterations: 2
    salt_length: 16
    key_length: 16

courier:
  smtp:
    connection_uri: smtps://test:test@localhost:1025/?skip_ssl_verify=true